### ISSUE TITLE
DOI Not Found

### ISSUE THREAD

**Issue by schwehr** [nick-murray/gee-global-intertidal-change-data-descriptor#1]
https://doi.org/10.1126/science.abm9583 gives `DOI Not Found`

**Comment by nick-murray** [comment]
DOI to go live when forthcoming manuscript is published online.


From: Kurt Schwehr ***@***.***>
Sent: Wednesday, 11 May 2022 6:10 AM
To: nick-murray/gee-global-intertidal-change-data-descriptor ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [nick-murray/gee-global-intertidal-change-data-descriptor] DOI Not Found (Issue #1)

This message was sent from someone external to JCU. Please do not click links or open attachments unless you recognise the source of this email and know the content is safe.

https://doi.org/10.1126/science.abm9583<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdoi.org%2F10.1126%2Fscience.abm9583&data=05%7C01%7Cnicholas.murray%40jcu.edu.au%7Cbce6a70397ea41633ed508da32c103a6%7C30a8c4e81ecd4f148099f73482a7adc0%7C0%7C0%7C637878101825293766%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TXfzlmca3PGbrzXEIGldjaNEDJqzLVovDueQ4vO7ZRw%3D&reserved=0> gives DOI Not Found

-

**Comment by schwehr** [comment]
Hey, Sorry for the bug.  I hadn't noticed that the paper was in the works.  I should have closed this bug when I noticed that a while back.
